// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBigF3VocfnvmAqYMsG5NvGxd8xA7c11nQ',
    appId: '1:973234871129:web:7e5406414abbbd0091ca48',
    messagingSenderId: '973234871129',
    projectId: 'cup-coffee-7dff9',
    authDomain: 'cup-coffee-7dff9.firebaseapp.com',
    storageBucket: 'cup-coffee-7dff9.appspot.com',
    measurementId: 'G-C8PDGY7Q25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxgVZ4eXleK1iZTY7m9MCdnbbImzAlFUU',
    appId: '1:973234871129:android:2abe1dba08119b2c91ca48',
    messagingSenderId: '973234871129',
    projectId: 'cup-coffee-7dff9',
    storageBucket: 'cup-coffee-7dff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDOXTUqPef71zftn357aHW_QeasK2PUsg',
    appId: '1:973234871129:ios:03c4117ff932db4a91ca48',
    messagingSenderId: '973234871129',
    projectId: 'cup-coffee-7dff9',
    storageBucket: 'cup-coffee-7dff9.appspot.com',
    iosClientId: '973234871129-tu329ckiteuda4vfloemqddm9aapifeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cupCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDOXTUqPef71zftn357aHW_QeasK2PUsg',
    appId: '1:973234871129:ios:03c4117ff932db4a91ca48',
    messagingSenderId: '973234871129',
    projectId: 'cup-coffee-7dff9',
    storageBucket: 'cup-coffee-7dff9.appspot.com',
    iosClientId: '973234871129-tu329ckiteuda4vfloemqddm9aapifeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cupCoffee',
  );
}
